name: Monitor iPhone 17 Pro Inventory

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  monitor:
    runs-on: ubuntu-latest
    env:
      ACTIONS_UPLOAD_DEPENDENCY_GRAPH: false  # 禁用依赖图上传

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Create config.json
        run: |
          cat > config.json << EOF
          {
            "appleTaskConfig": {
              "cronExpressions": "0/5 * * * * ?",
              "country": "CN",
              "location": "湖南 长沙",
              "deviceCodeList": [
                {
                  "deviceCode": "MG8T3CH/A",
                  "storeWhiteList": [],
                  "pushConfigs": [
                    {
                      "barkPushUrl": "https://api.day.app/push",
                      "barkPushToken": "${{ secrets.BARK_TOKEN }}",
                      "barkPushSound": "multiwayinvitation.caf",
                      "feishuBotWebhooks": "",
                      "feishuBotSecret": ""
                    }
                  ]
                }
              ]
            }
          }
          EOF

      - name: Run Apple Monitor
        run: |
          JAR_FILE=$(ls target/*.jar | head -1)
          if [ -z "$JAR_FILE" ]; then
            echo "No JAR file found in target/. Build failed?"
            exit 1
          fi
          echo "Running $JAR_FILE..."
          java -jar "$JAR_FILE"
        timeout-minutes: 10